//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENTS
    {
        public int ID_AGENT { get; set; }
        public Nullable<int> ID_BASE { get; set; }
        public string A_NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<int> PHONE_NUMBER { get; set; }
        public Nullable<int> SALARY { get; set; }
    
        public virtual BASE BASE { get; set; }
    }
}
