//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR()
        {
            this.ORDERS = new HashSet<ORDERS>();
            this.ORDERS_ARCHIVE = new HashSet<ORDERS_ARCHIVE>();
            this.REPAIRS = new HashSet<REPAIRS>();
        }
    
        public int ID_CAR { get; set; }
        public Nullable<int> ID_BASE { get; set; }
        public string MARK { get; set; }
        public string C_MODEL { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public Nullable<int> RENT_PRICE { get; set; }
        public string C_CATEGORY { get; set; }
        public Nullable<int> PRODUCTION_YEAR { get; set; }
    
        public virtual BASE BASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_ARCHIVE> ORDERS_ARCHIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRS> REPAIRS { get; set; }
    }
}
