//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class MECHANICS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MECHANICS()
        {
            this.REPAIRS = new HashSet<REPAIRS>();
        }
    
        public int ID_MECHANIC { get; set; }
        public Nullable<int> ID_BASE { get; set; }
        public string M_NAME { get; set; }
        public string SURNAME { get; set; }
        public Nullable<int> PHONE_NUMBER { get; set; }
        public Nullable<System.DateTime> HIREDATE { get; set; }
        public Nullable<int> SALARY { get; set; }
    
        public virtual BASE BASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRS> REPAIRS { get; set; }
    }
}
